Update nutcracker.init

diff --git a/scripts/nutcracker.init b/scripts/nutcracker.init
--- a/scripts/nutcracker.init
+++ b/scripts/nutcracker.init
@@ -1,73 +1,58 @@
 #! /bin/sh
-#
-# chkconfig: - 55 45
-# description:  Twitter's twemproxy nutcracker
-# processname: nutcracker
-# config: /etc/sysconfig/nutcracker
-
-# Source function library.
-. /lib/lsb/init-functions
-
-USER="nobody"
-OPTIONS="-d -c /etc/nutcracker.yaml -o /var/log/nutcracker/nutcracker.log"
-
-if [ -f /etc/sysconfig/nutcracker ];then
-    . /etc/sysconfig/nutcracker
-fi
-
-# Check that networking is up.
-if [ "$NETWORKING" = "no" ]
-then
-    exit 0
-fi
-
-RETVAL=0
-prog="nutcracker"
-
-start () {
-    echo -n $"Starting $prog: "
-    ${prog} $OPTIONS
-    RETVAL=$?
-    echo
-    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/${prog}
-}
-stop () {
-    echo -n $"Stopping $prog: "
-    killproc ${prog}
-    RETVAL=$?
-    echo
-    if [ $RETVAL -eq 0 ] ; then
-        rm -f /var/lock/subsys/${prog}
-    fi
-}
-
-restart () {
-    stop
-    start
-}
-
-
-# See how we were called.
+### BEGIN INIT INFO
+# Provides:		    nutcracker
+# Required-Start:	$syslog
+# Required-Stop:	$syslog
+# Should-Start:		$local_fs
+# Should-Stop:		$local_fs
+# Default-Start:	2 3 4 5
+# Default-Stop:		0 1 6
+# Short-Description:	nutcracker - Twitter redis proxy
+# Description:		    nutcracker - Twitter redis proxy
+### END INIT INFO
+ 
+ 
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/local/sbin/nutcracker
+DAEMON_ARGS=-d -c /etc/nutcracker.yaml -o /var/log/nutcracker/nutcracker.log -p /var/run/nutcracker.pid
+NAME=nutcracker
+DESC=nutcracker
+PIDFILE=/var/run/nutcracker.pid
+ 
+test -x $DAEMON || exit 0
+ 
+set -e
+ 
 case "$1" in
   start)
-    start
-    ;;
+	echo -n "Starting $DESC: "
+	touch $PIDFILE
+	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	;;
   stop)
-    stop
-    ;;
-  status)
-    status ${prog}
-    ;;
-  restart|reload)
-    restart
-    ;;
-  condrestart)
-    [ -f /var/lock/subsys/nutcracker ] && restart || :
-    ;;
+	echo -n "Stopping $DESC: "
+	if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	rm -f $PIDFILE
+	;;
+ 
+  restart|force-reload)
+	${0} stop
+	${0} start
+	;;
   *)
-    echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
-    exit 1
+	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
+	exit 1
+	;;
 esac
-
-exit $?
-
+ 
+exit 0
